server:
  port: 2024

spring:

#  NoSQL
  data:
    mongodb:
      host: localhost
      port: 27017
      database: mongotoken
      username: tokenmongo
      password: tokenmongo

# SQL
  datasource:
    url: jdbc:mysql://localhost:3306/jwttechnologies
    username: root
    password: faolseans8246
    driver-class-name: com.mysql.cj.jdbc.Driver

    hikari:
      pool-name: MyHikariCP
      maximum-pool-size: 10

  main:
    allow-bean-definition-overriding: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

#    Security
  security:
    user:
      name: login
      password: parol

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
